language: python
python:
  - 3.7.5
before_install:
  - git remote -v  
  - ssh-keygen -P "" -f $HOME/.ssh/id_rsa  -C $HOME/.ssh/id_rsa.pub 
  #- ssh-keygen -P "" -f id_rsa  -C id_rsa.pub  
  - cat $HOME/.ssh/id_rsa.pub 
  - cat $HOME/.ssh/id_rsa	
  ### 安裝
  - uname -r
  - which curl
  - curl -fsSL https://get.docker.com/ | sh
  - sudo usermod -aG docker travis
  - docker -v
  - docker run hello-world
  ### end
 
  #- find / -type f -name  id_rsa.pub    
  #- cat $HOME/.ssh/id_rsa.pub   
  - ls -al $HOME/.ssh    
  - python --version
  - pip install -U pip
  #- pip install -U pytest
  
  - echo $HOME 
  #-/home/travis
  - pwd
  - cp LINUX.travis  QQ.ttt
  - chown --help
  - ls -al
  - pip install -r requirements.txt
install:
  - pip install -r requirements.txt
  - pip3 install codecov
#script: exit 0
script: python3 A.py || python B.py
after_success: python 3 -m codecov
