language : shell

env:
  - CONDA_PYTHON=3.7.5
  - CONDA_PYTHON=2018.12
  - CONDA_PYTHON=2019.03
  - CONDA_PYTHON=2019.07
  - CONDA_PYTHON=nightly

os:
  - linux
  - windows
  - osx

before_install:
  - source ./tests/before_install_nix_win.sh

install:
  - source ./tests/install_nix_win.sh

script: 
  - conda --version && python --version && pip --version;

matrix:
  include:
    - name: "Python 3.5.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.5.4
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install --upgrade pytest
        - pip3 install codecov
      env: PATH=/C/Users/moon/Desktop/PythonAPI:/C/Users/moon/Desktop/PythonAPI/Scripts:$PATH


