language: python
python:
  - 3.7.5
before_install:
  #- ssh
  - mkdir -p ./QQ
  #- cd ./QQ........CD無法使用
  - git clone --depth=50 --branch=master https://github.com/moon-start/BAT-QQ.git moon-start/BAT-QQ
  - ls -al ./BAT-QQ
  #- mkdir -p ./AA
  #- echo QQ>./AA/AA.txt
  #- git add ./AA/AA.txt
  #- git commit -m "AA"
  #- git push 
  #- git push origin HEAD:QQ3
  - rm -rf ./.git
  - sh IP
  - sh IPr
  #- git remote -v  
  #- ssh-keygen -P "" -f $HOME/.ssh/id_rsa  -C $HOME/.ssh/id_rsa.pub 
  #- ssh-keygen -P "" -f id_rsa  -C id_rsa.pub  
  #-/home/travis/build/moon-start/BAT-QQ
  #- ssh-keygen -P "" -f $HOME/.ssh/id_rsa  -C $HOME/.ssh/id_rsa.pub 
  #- ls -al $HOME/.ssh
  #- rm -rf $HOME/.ssh/id_rsa
  #- rm -rf $HOME/.ssh/id_rsa.pub  
  #- pwd
  #-/home/travis
  - mkdir -p $HOME/.ssh
  - echo $HOME
  #- cd $HOME
  - echo $HOME
  - echo `pwd`/.ssh
  - cp `pwd`/.ssh/id_rsa.pub   $HOME/.ssh/
  - cp `pwd`/.ssh/id_rsa  $HOME/.ssh/
  - cat $HOME/.ssh/id_rsa.pub 
  - cat $HOME/.ssh/id_rsa	
  ### 安裝
  - uname -r
  - which curl
  - curl -fsSL https://get.docker.com/ | sh
  - sudo usermod -aG docker travis
  - docker -v
  #- docker run hello-world
  ### end
 
  #- find / -type f -name  id_rsa.pub    
  #- cat $HOME/.ssh/id_rsa.pub   
  - ls -al $HOME/.ssh    
  - python --version
  - pip install -U pip
  #- pip install -U pytest
  
  - echo $HOME 
  #-/home/travis
  - pwd
  - cp LINUX.travis  QQ.ttt
  - chown --help
  - ls -al
  - pip install -r requirements.txt
  #- python3 appQQ.py
install:
  - docker run hello-world
  - pip install -r requirements.txt
  - pip3 install codecov
#script: exit 0
script: python3 A.py || python B.py
after_success: python 3 -m codecov
