language: python            # this works for Linux but is an error on macOS or Windows
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
      env:
       - CONDA_PYTHON=3.7.5
       - CONDA_PYTHON=nightly
      before_install:
  	- python --version
  	- pip install -U pip
  	#- pip install -U pytest
  	#- git remote -v
  	- pip install -r requirements.txt
      install:
  	- pip install -r requirements.txt


    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS


    - name: "Python 3.7.5 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7.5
  	- python --version
        #- python -m pip install --upgrade pip
        - git --version
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

install: pip3 install --upgrade pip  # all three OSes agree about 'pip3'
# 'python' points to Python 2.7 on macOS but points to Python 3.8 on Linux and Windows
# 'python3' is a 'command not found' error on Windows but 'py' works on Windows only
script: python3 A.py || python B.py
