language: python
python:
  - 3.7.5
before_install:
  - python --version
  - pip install -U pip
  #- pip install -U pytest
  - git remote -v
  - echo $HOME
  #-/home/travis
  - pwd
  - cp LINUX.travis  QQ.ttt
  - chown --help
  - ls -al
  - pip install -r requirements.txt
install:
  - pip install -r requirements.txt
  - pip3 install codecov
#script: exit 0
script: python3 A.py || python B.py
after_success: python 3 -m codecov
